#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Mar  7 18:44:34 2021

@author: ElishaYi
"""
#輸入迴圈次數，計算數值中為偶數的加總，最後印出加總的值

total=0
number = int(input("請輸入次數:"))
for i in range (1,number+1):
    if i %2 == 0:
       print(i)
       total += i
        
print("偶數加總：",total)

"""
a=0
number = int(input("請輸入次數:"))
for i in range (1,number+1):
    if i %2 == 0:
       print(i)
       a += i
       print(a)
       
print("偶數加總：",a)
"""
